# Problem 56
Given a `N` by `M` matrix of numbers, print out the matrix in a clockwise spiral.

For example, given the following matrix:
```
[[1,  2,  3,  4,  5],
 [6,  7,  8,  9,  10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20]]
 ```
You should print out the following:
```
1
2
3
4
5
10
15
20
19
18
17
16
11
6
7
8
9
14
13
12
```

---
## Solution

In [119]:
# solution code
import numpy as np

def NxM_Matrix(N, M):
    matrix = []
    count = 1
    for j in range(M):
        row = []
        for i in range(N):
            row.append(count)
            count+=1
        matrix.append(row)
    return matrix

def spriral_print(matrix):
    spiraling = True
    left = 0
    right = len(matrix[0])-1
    top = 0
    bottom = len(matrix)-1

    while(spiraling):
    
        # print top row
        for i in range(left, right+1):
            print(matrix[top][i])
        top += 1
        
        # print right column
        for i in range(top, bottom+1):
            print(matrix[i][right])
        right -= 1
        
        # print bottom row
        for i in range(right, left-1, -1):
            print(matrix[bottom][i])
        bottom -= 1
        
        # print left column
        for i in range(bottom, top-1, -1):
            print(matrix[i][left])
        left += 1
        
        # check if all elements have been printed
        if left > right or top > bottom:
            spiraling = False



---
## Test Cases

In [120]:
# solution testing test cases
matrix = NxM_Matrix(5, 4)
print(np.matrix(matrix), "\n")
spriral_print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

1
2
3
4
5
10
15
20
19
18
17
16
11
6
7
8
9
14
13
12


In [121]:
matrix = NxM_Matrix(4, 5)
print(np.matrix(matrix), "\n")
spriral_print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]] 

1
2
3
4
8
12
16
20
19
18
17
13
9
5
6
7
11
15
14
10


In [122]:
matrix = NxM_Matrix(6, 6)
print(np.matrix(matrix), "\n")
spriral_print(matrix)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]] 

1
2
3
4
5
6
12
18
24
30
36
35
34
33
32
31
25
19
13
7
8
9
10
11
17
23
29
28
27
26
20
14
15
16
22
21


---
## Solution Explained

### `spriral_print(matrix)` solution
This code implements a solution to the problem of printing out a given `N` by `M` matrix in a clockwise spiral order.

The first function `NxM_Matrix` creates an `N` by `M` matrix with sequential numbers starting from 1. The function uses nested loops to create the `matrix` and returns it.

The second function `spriral_print` implements the spiral printing algorithm. The function initializes variables `left`, `right`, `top`, and `bottom` to represent the boundaries of the `matrix`. The while loop executes until all elements have been printed. In each iteration of the loop, the function prints the top row, right column, bottom row, and left column of the `matrix` in that order, using for loops. The variables `left`, `right`, `top`, and `bottom` are updated after each iteration to exclude the printed rows and columns. The loop continues until `left` becomes greater than `right` or `top` becomes greater than `bottom`.

The time complexity of this algorithm is O(NM), where `N` and `M` are the dimensions of the matrix. This is because the algorithm has to visit every element in the matrix once to print them. The space complexity of the algorithm is O(1), since it only uses a constant amount of extra memory to store the variables.